### ISSUE TITLE
Cyrillic glyphs

### ISSUE THREAD

**Issue by rellikmil** [Josef-Friedrich/interfectorB#1]

**Comment by Josef-Friedrich** [comment]
Pull request?

**Comment by rellikmil** [comment]
Eeeeeem, no. But I can try to do it myself, with your help.

**Comment by rellikmil** [comment]
When I finished my list of fonts, I`ll do Cyrillic for this font

**Comment by rellikmil** [comment]
@Josef-Friedrich Do you have any idea to how draw Д?
![изображение](https://user-images.githubusercontent.com/24569064/63226550-a6b30d80-c1e3-11e9-8836-9106174b405b.png)

**Comment by rellikmil** [comment]
yeah, some straight lines is not straight, but but I'm working on it
